name: adder
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  hex: ^0.1.2
  protobuf: ^1.1.3
  fixnum: ^0.10.9
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.adder
    pluginClass: AdderPlugin
